make PCB=MEGA2560 TRANSLATIONS=FR LCD=KS108 TEMPLATES=YES NAVIGATION=NO HELI=YES GVARS=YES GPS=NO EEPROM_PROGRESS_BAR=YES DEFAULT_MODE=2 DBLKEYS=YES CURVES=YES AUTOSWITCH=YES AUTOSOURCE=YES HAPTIC=NO PPM_CENTER_ADJUSTABLE=YES PM_LIMITS_SYMETRICAL=YES PPM_UNIT=PERCENT_PREC1 SDCARD=YES AUDIO=YES VOICE=YES BATTGRAPH=YES HARDWARE_VOLUME=NO JITTER_FILTER=NO EXT=FRSKY SPLASH=YES
pause
