make PCB=MEGA2560 TRANSLATIONS=FR LCD=ST7920 HELI=NO TEMPLATES=NO CURVES=YES SDCARD=YES HAPTIC=NO PPM_CENTER_ADJUSTABLE=YES GVARS=YES AUTOSOURE=YES AUTOSWITCH=YES DBLKEYS=YES BATTGRAPH=YES EEPROM_PROGRESS_BAR=YES PPM_UNIT=US AUDIO=YES VOICE=YES DEFAULT_MODE=1 NAVIGATION=NO GPS=NO SPLASH=YES EXT=FRSKY
pause
